<?php

return [
    'guest' => [
        [
            'type' => 'link',
            'label' => 'menu.guest.home',
            'route' => 'home',
            'icon' => 'tabler-smart-home',
            'active' => ['home'],
        ],
        [
            'type' => 'header',
            'label' => 'menu.headers.public_portal',
        ],
        [
            'type' => 'link',
            'label' => 'menu.guest.login',
            'route' => 'login',
            'icon' => 'tabler-login',
            'active' => ['login'],
        ],
        [
            'type' => 'link',
            'label' => 'menu.guest.register',
            'route' => 'register',
            'icon' => 'tabler-user-plus',
            'active' => ['register'],
        ],
        [
            'type' => 'link',
            'label' => 'menu.guest.verify_certificate',
            'route' => 'verify.certificate',
            'route_params' => ['hash' => 'semak'],
            'icon' => 'tabler-certificate',
            'active' => ['verify.certificate'],
        ],
    ],

    'student' => [
        [
            'type' => 'link',
            'label' => 'menu.student.dashboard',
            'route' => 'student.dashboard',
            'icon' => 'tabler-dashboard',
            'active' => ['student.dashboard'],
        ],
        [
            'type' => 'header',
            'label' => 'menu.headers.learning',
        ],
        [
            'type' => 'link',
            'label' => 'menu.student.courses',
            'route' => 'student.courses',
            'icon' => 'tabler-books',
            'active' => ['student.courses', 'student.apply', 'student.course.detail', 'student.my-courses', 'student.applications'],
        ],
        [
            'type' => 'link',
            'label' => 'menu.student.schedule',
            'route' => 'student.schedule',
            'icon' => 'tabler-calendar',
            'active' => ['student.schedule'],
        ],
        [
            'type' => 'link',
            'label' => 'menu.student.attendance',
            'route' => 'student.attendance',
            'icon' => 'tabler-user-check',
            'active' => ['student.attendance'],
        ],
        [
            'type' => 'link',
            'label' => 'menu.student.academic',
            'route' => 'student.academic',
            'icon' => 'tabler-school',
            'active' => ['student.academic'],
        ],
        [
            'type' => 'link',
            'label' => 'menu.student.talaqqi',
            'route' => 'student.talaqqi.book',
            'icon' => 'tabler-calendar-time',
            'active' => ['student.talaqqi.book'],
            'visible_when' => 'has_talaqqi_enrollment',
        ],
    ],

    'teacher' => [
        [
            'type' => 'link',
            'label' => 'menu.teacher.dashboard',
            'route' => 'teacher.dashboard',
            'icon' => 'tabler-dashboard',
            'active' => ['teacher.dashboard'],
        ],
        [
            'type' => 'header',
            'label' => 'menu.headers.teaching',
        ],
        [
            'type' => 'link',
            'label' => 'menu.teacher.schedules',
            'route' => 'teacher.schedules',
            'icon' => 'tabler-calendar-plus',
            'active' => ['teacher.schedules'],
        ],
        [
            'type' => 'link',
            'label' => 'menu.teacher.attendance',
            'route' => 'teacher.attendance',
            'icon' => 'tabler-user-check',
            'active' => ['teacher.attendance'],
        ],
        [
            'type' => 'link',
            'label' => 'menu.teacher.grades',
            'route' => 'teacher.grades',
            'icon' => 'tabler-license',
            'active' => ['teacher.grades'],
        ],
        [
            'type' => 'link',
            'label' => 'menu.teacher.placement_tests',
            'route' => 'teacher.placement-tests',
            'icon' => 'tabler-microphone',
            'active' => ['teacher.placement-tests'],
        ],
        [
            'type' => 'link',
            'label' => 'menu.teacher.talaqqi',
            'route' => 'teacher.talaqqi.session',
            'icon' => 'tabler-book-open',
            'active' => ['teacher.talaqqi.session'],
        ],
        [
            'type' => 'link',
            'label' => 'menu.teacher.students',
            'route' => 'teacher.students',
            'icon' => 'tabler-users',
            'active' => ['teacher.students'],
        ],
    ],

    'admin' => [
        [
            'type' => 'link',
            'label' => 'menu.admin.dashboard',
            'route' => 'admin.dashboard',
            'icon' => 'tabler-dashboard',
            'active' => ['admin.dashboard'],
        ],
        [
            'type' => 'header',
            'label' => 'menu.headers.user_management',
        ],
        [
            'type' => 'link',
            'label' => 'menu.admin.enrollments',
            'route' => 'admin.enrollments',
            'icon' => 'tabler-school',
            'active' => ['admin.enrollments'],
        ],
        [
            'type' => 'link',
            'label' => 'menu.admin.lecturers',
            'route' => 'admin.lecturers',
            'icon' => 'tabler-users',
            'active' => ['admin.lecturers'],
        ],
        [
            'type' => 'link',
            'label' => 'menu.admin.admins',
            'route' => 'admin.admins',
            'icon' => 'tabler-settings',
            'active' => ['admin.admins'],
        ],
        [
            'type' => 'header',
            'label' => 'menu.headers.application_exam',
        ],
        [
            'type' => 'link',
            'label' => 'menu.admin.applications',
            'route' => 'admin.applications',
            'icon' => 'tabler-clipboard-list',
            'active' => ['admin.applications'],
        ],
        [
            'type' => 'link',
            'label' => 'menu.admin.placement_tests',
            'route' => 'admin.placement-tests',
            'icon' => 'tabler-microphone',
            'active' => ['admin.placement-tests'],
        ],
        [
            'type' => 'header',
            'label' => 'menu.headers.enrollment_payment',
        ],
        [
            'type' => 'link',
            'label' => 'menu.admin.payments',
            'route' => 'admin.payments',
            'icon' => 'tabler-credit-card',
            'active' => ['admin.payments'],
        ],
        [
            'type' => 'header',
            'label' => 'menu.headers.learning',
        ],
        [
            'type' => 'link',
            'label' => 'menu.admin.schedules',
            'route' => 'admin.schedules',
            'icon' => 'tabler-calendar',
            'active' => ['admin.schedules'],
        ],
        [
            'type' => 'link',
            'label' => 'menu.admin.attendance',
            'route' => 'admin.attendance',
            'icon' => 'tabler-chart-dots',
            'active' => ['admin.attendance'],
        ],
        [
            'type' => 'link',
            'label' => 'menu.admin.academic',
            'route' => 'admin.academic',
            'icon' => 'tabler-school',
            'active' => ['admin.academic'],
        ],
        [
            'type' => 'header',
            'label' => 'menu.headers.certification_reports',
        ],
        [
            'type' => 'link',
            'label' => 'menu.admin.certificates',
            'route' => 'admin.certificates',
            'icon' => 'tabler-certificate',
            'active' => ['admin.certificates'],
        ],
        [
            'type' => 'link',
            'label' => 'menu.admin.courses',
            'route' => 'admin.courses',
            'icon' => 'tabler-books',
            'active' => ['admin.courses'],
        ],
        [
            'type' => 'link',
            'label' => 'menu.admin.reports',
            'route' => 'admin.reports',
            'icon' => 'tabler-chart-bar',
            'active' => ['admin.reports'],
        ],
        [
            'type' => 'link',
            'label' => 'menu.admin.verify_certificate',
            'route' => 'verify.certificate',
            'route_params' => ['hash' => 'semak'],
            'icon' => 'tabler-search',
            'active' => ['verify.certificate'],
        ],
    ],
];
